a = int(input())
b = int(input())
c = int(input())
d = int(input())
e = int(input())

print("SUM", a+b+c+d+e)
print("MAX", max(a,b,c,d,e))
print("MIN", min(a,b,c,d,e))
print("MEAN", (a+b+c+d+e)/5)
